### ISSUE TITLE
One build test fails and program crashes on start

### ISSUE THREAD

**Issue by aufkrawall** [DelusionalLogic/NeoComp#11]
As asked in #9 , a new ticket for this issue.
Arch Linux with latest packages. Mesa is built from -git, but shows no difference vs. stable versions.

When compiling with PKGBUILD, one of the tests fails with this error:
>✗ A bezier won't get 1 for 1 when querying on nonlinear curve
>        By floating equality test on v 1.000000==1.000000 

When skipping the tests via `--nocheck`, it compiles. Then it crashes on start (no config specified):
> $ neocomp
[     0.00 ] error    2 BadValue     request  138 minor    7 serial     10: "BadValue (integer parameter out of range for operation)"
assets_add_path(): Using asset path ./assets/
assets_add_path(): Using asset path /home/USER/.config//neocomp/assets/
assets_add_path(): Using asset path /etc/xdg//neocomp/assets/
Opengl version 4.5 (Core Profile) Mesa 19.0.0-devel (git-e869481ef3)
Xorg Features: 
    Composite: 0.2+
    XFIXES: YES
    DAMAGE: YES
    RENDER: YES
    SHAPE: YES
    RANDR: YES
    GLX: YES
    XINERAMA: YES
    SYNC: YES
[     0.04 ] error    2 BadValue     request  142 minor    3 serial     95: "BadValue (integer parameter out of range for operation)"
neocomp: src/framebuffer.c:20: framebuffer_resetTarget: Zusicherung »framebuffer->gl_fbo != 0« nicht erfüllt.
> Abgebrochen (Speicherabzug geschrieben)

This is with RX 580 & Mesa:
> $ xdpyinfo -queryExt | grep opcode
    BIG-REQUESTS  (opcode: 133)
    Composite  (opcode: 142)
    DAMAGE  (opcode: 143, base event: 91, base error: 152)
    DOUBLE-BUFFER  (opcode: 145, base error: 153)
    DPMS  (opcode: 147)
    DRI2  (opcode: 155, base event: 119)
    DRI3  (opcode: 149)
    GLX  (opcode: 152, base event: 95, base error: 158)
    Generic Event Extension  (opcode: 128)
    MIT-SCREEN-SAVER  (opcode: 144, base event: 92)
    MIT-SHM  (opcode: 130, base event: 65, base error: 128)
    Present  (opcode: 148)
    RANDR  (opcode: 140, base event: 89, base error: 147)
    RECORD  (opcode: 146, base error: 154)
    RENDER  (opcode: 139, base error: 142)
    SECURITY  (opcode: 137, base event: 86, base error: 138)
    SHAPE  (opcode: 129, base event: 64)
    SYNC  (opcode: 134, base event: 83, base error: 134)
    X-Resource  (opcode: 150)
    XC-MISC  (opcode: 136)
    XFIXES  (opcode: 138, base event: 87, base error: 140)
    XFree86-DGA  (opcode: 154, base event: 112, base error: 179)
    XFree86-VidModeExtension  (opcode: 153, base error: 172)
    XINERAMA  (opcode: 141)
    XInputExtension  (opcode: 131, base event: 66, base error: 129)
    XKEYBOARD  (opcode: 135, base event: 85, base error: 137)
    XTEST  (opcode: 132)
>    XVideo  (opcode: 151, base event: 93, base error: 155)

**Comment by DelusionalLogic** [comment]
Those are both very strange issues indeed.

I'll have a look, but could you attach the coredump from the crash (preferably built in debug mode, without stripping). I don't understand how that framebuffer object ends up being 0.

**Comment by aufkrawall** [comment]
Thank you. I found out that `--blur-background=true`must be used, else NeoComp crashes.

**Comment by DelusionalLogic** [comment]
That's bad. Thanks for doing the bug hunting for me :) I'll get it fixed.

**Comment by aufkrawall** [comment]
Nice! :)
Just in case, I think I can manage to provide dumps tomorrow. It was already a cool feeling to have compositing with just minimal input latency.

**Comment by aufkrawall** [comment]
Here is one crash dump for a crash with `--blur-background=false` and one with `=true` which occurred after starting mpv:
https://www.mediafire.com/file/1bf99b17c5f1tgd/crashdumps.7z/file

**Comment by DelusionalLogic** [comment]
I'm going to close this now. I never figured out what caused it, but the code has diverged to a point where it's probably not relevant anymore.
