### ISSUE TITLE
Have you heard about this project ?

### ISSUE THREAD

**Issue by TLogiviere** [DelusionalLogic/NeoComp#23]
Hello DelusionalLogic,

Out of curiosity, have you heard about yshui/picom project ?
There seems to happen a similar work to yours ; Maybe the community could benefit from the GCD of both projects ?

**Comment by DelusionalLogic** [comment]
Sorry about leaving this for 6 months. I'm not good at checking out my issues.

I have heard about picom. It seems to be a more conservative project that seems to be trying to remain useful and backwards compatible. NeoComp is intended as a longer term "Moonshot" project. I've spent a scary amount of time ripping out everything i could and rewriting the rest. I've been at this for 2.5 years (2 years when you wrote this), and unfortunately that means our codebases have diverged a lot.

I appreciate your sentiment. I'm very open to talking to the picom guys if they want to discuss anything. I bet we have a lot to talk about :).

I'm going to close this as it isn't really an issue :) Again, thanks for your time. It feels good to be seen in the world.
